apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xray
  namespace: xray
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  ingressClassName: nginx
  rules:
    - host: <your-gateway-subdomain.your-domain.com>
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: xray
                port:
                  number: 10000
